### ISSUE TITLE
simplefix has no attribute "Message"

### ISSUE THREAD

**Issue by YaraAmin** [da4089/simplefix#19]
when i try to create new message using : "fix_msg = simplefix.Message()" an error pop up as:
"File "C:/simplefix-master/simplefix/simple.py", line 4, in <module>
    fix_msg = simplefix.Message()
AttributeError: module 'simplefix' has no attribute 'Message'"

and please may you explain the difference between "SIMPLEFIX" and "QUICKFIX" or put any links for atricles

**Comment by da4089** [comment]
It appears that the interpreter has found a "simplefix" module, but that probably it's not the actual simplefix package (which is why the attribute lookup is failing).

That might mean it's  found a `simplefix.py` file in the import path, before it has found the actual package directory?   You could check this by inserting `print(simplefix.__file__)` before line 4.


Regarding QuickFIX: simplefix is very *simple*.  It converts FIX messages into a Python `Message` class, and those Python class instances into FIX messages.  QuickFIX is a complete FIX engine, which includes connection handling, message validation, session management, persistence, and many other features.

**Comment by da4089** [comment]
Closing this.  If you need further help, please re-open.
