### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MalakaPunche** [da4089/simplefix#61]
I'm a student and I am trying to use simplefix but having difficulties installing it because of quickfix issue, could you guide me on how to solve the issue
![image](https://github.com/user-attachments/assets/dc10c0b8-1447-4250-ad6a-58e9cd223b7f)

**Comment by da4089** [comment]
Looking at that image, it appears that the problem is with QuickFIX (although the SimpleFIX output is truncated, so perhaps it had an issue as well?)

SimpleFIX does not require QuickFIX as a dependency: if you want to use SimpleFIX, you can install it independently.

I cannot help with QuickFIX issues: you should contact that project directly.  At first glance, it looks like the QuickFIX Visual Studio solution might not be compatible with VS2022, but that's something the QuickFIX folks would be much more in a position to help with.

If you did have a problem with SimpleFIX, please include the output and reopen this issue.
